### PR TITLE
update error detail handling

### LINKED ISSUE #221: crosstest-go workflow has failed
The most recent run of crosstest-go has failed, please investigate.

### PR DESCRIPTION
**Pull request by cyinma**
fixes #221

### CODE REVIEW

**Comment by akshayjshah** [comment]
This is awesome, @cyinma - I didn't even realize that you'd already started working on it ;) I pushed a commit to make the new Go code a little less verbose, and then a commit that removes all the NPM token and branch-testing stuff. If we still want support for testing branches, feel free to revert the last commit. (I think we need _some_ way to test unreleased connect-web and protobuf-es code, but there were TODO comments suggesting that I should delete it - maybe there's some other way to install unreleased NPM stuff?)

@timostamm is planning to push a new version of `connect-web` tomorrow morning. We'll then update the pinned version here and make sure everything passes. If there are any bugs, we can push a patch release of `connect-{go,web}`. I'll be on a flight for most of the day, but I should have wifi.

**Comment by cyinma** [comment]
> This is awesome, @cyinma - I didn't even realize that you'd already started working on it ;) I pushed a commit to make the new Go code a little less verbose, and then a commit that removes all the NPM token and branch-testing stuff. If we still want support for testing branches, feel free to revert the last commit. (I think we need _some_ way to test unreleased connect-web and protobuf-es code, but there were TODO comments suggesting that I should delete it - maybe there's some other way to install unreleased NPM stuff?)
> 
> @timostamm is planning to push a new version of `connect-web` tomorrow morning. We'll then update the pinned version here and make sure everything passes. If there are any bugs, we can push a patch release of `connect-{go,web}`. I'll be on a flight for most of the day, but I should have wifi.

I think we still need the branch-testing stuff, as that is what nightly crosstest using? but those NPM token stuff can be removed

**Review by timostamm — APPROVED** [review]
I've updated the connect-web runtime libraries specified in package.json, and we got a green checkmark.

**Comment by timostamm** [comment]
There is a slight hiccup in the BSR plugin process (see BSR-395), so I couldn't update the code generators in buf.gen.yaml.
Merging this so the new crosstest server image gets pushed.

**Pull request merged**
